[build]
  command = "yarn generate"
  publish = "dist"

[[redirects]]
  from = "/"
  to = "https://www.d-hagemeier.com/"
  status = 301
  force = true

[[plugins]]
  package = "netlify-plugin-gatsby-cache"