[build]
  command = "yarn generate"
  publish = "public"

[[plugins]]
package = "./plugins/cache-directory"
  [plugins.inputs]
    cacheDir = "/cache"

[[redirects]]
  from = "https://d-hagemeier-previewimages.netlify.app/"
  to = "https://www.d-hagemeier.com/"
  status = 301
  force = true
